* **Module Code:** B9DA108
* **Module Title:** Programming for Data Analysis

# **What is Python?**

Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.


# **What Can Python Do?**

   * Python can be used on a server to create web applications.
   * Python can be used alongside software to create workflows.
   * Python can connect to database systems. It can also read and modify files.
   * Python can be used to handle big data and perform complex mathematics.
   * Python can be used for rapid prototyping, or for production-ready software development.


# **Why Python?**

   * Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).
   * Python has a simple syntax similar to the English language.
   * Python has syntax that allows developers to write programs with fewer lines than some other programming languages.
   * Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.
   * Python can be treated in a procedural way, an object-oriented way or a functional way.



# **Python Syntax compared to other programming languages**


  * Python was designed for readability, and has some similarities to the English language with influence from mathematics.
  *  Python uses new lines to complete a command, as opposed to other programming languages which often use semicolons or parentheses.
  *  Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes. Other programming languages often use curly-brackets for this purpose.


In [ ]:
print("Hello, World!")

Hello, World!


In [ ]:
2+3

5

In [ ]:
4*5

20

In [ ]:
print(45-5)

40


# **Python Indentation**
Indentation refers to the spaces at the beginning of a code line.

Where in other programming languages the indentation in code is for readability only, the indentation in Python is very important.

Python uses indentation to indicate a block of code.

In [ ]:
if 5>7:
  print("Anything")

In [ ]:
if 6>3:
  print("Today is Friday")

Today is Friday


Python will give you an error if you skip the indentation:

In [ ]:
if 5 > 2:
print("Five is greater than two!")

IndentationError: expected an indented block after 'if' statement on line 1 (<ipython-input-7-a314491c53bb>, line 2)

In [ ]:
if True:
   print ("True")
else:
   print ("False")

True


In [ ]:
if True:

print ("True")
else:
  print ("False")

IndentationError: expected an indented block after 'if' statement on line 1 (<ipython-input-10-4a505e8e0366>, line 3)

**Comments in Python**

In [ ]:
# This is a single-line comment
x = 10  # This comment explains the variable assignment
print(x)  # Output the value of x


10


In [ ]:
x = 10  # Initialize variable x with value 10
y = 20  # Initialize variable y with value 20
result = x + y  # Calculate the sum of x and y
print(result)  # Print the result


30


**Multi-line comments**

In [ ]:
# This is a multi-line comment.
# It spans multiple lines,
# providing a detailed explanation.

In [ ]:
# Using double quotes
double_quoted_string = "Python's syntax is clean and easy to learn."
print(double_quoted_string)

Python's syntax is clean and easy to learn.


In [ ]:
# Using triple quotes
triple_quoted_string = '''This is a multi-line string.
It can span multiple lines,
and include both "double" and 'single' quotes.'''
print(triple_quoted_string)

This is a multi-line string.
It can span multiple lines,
and include both "double" and 'single' quotes.


In [ ]:
# Variable assignment
x = 5

# Print statement
print(x)

# Function call
def greet():
    print("Hello, World!")

greet()

5
Hello, World!


In [ ]:
# This is a comment
# This line of code prints
# Hello World
# Name: Sree Aakash
# Student number:
# Module Code:
print("Hello, World!")

In [ ]:
print("Hello, World!") #This is a comment

Hello, World!


**Using Python as a Calculator**

**1. Numbers**

In [ ]:
7+6

13

In [ ]:
15+12

27

In [ ]:
x+5

15

In [ ]:
s=17
s+6

23

In [ ]:
2+5

7

In [ ]:
(50-5*6)//4

5

In [ ]:
8/6

1.3333333333333333

In [ ]:
8//6 #Floor division discards the fractional part

1

In [ ]:
5/4

1.25

In [ ]:
17%5 #Returns the remainder

2

In [ ]:
5*3+2

17

# **Creating Variables**

* Python has no command for declaring a variable.

* A variable is created the moment you first assign a value to it.

**Variable Names**
* A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume). Rules for Python variables:

    * A variable name must start with a letter or the underscore character
    * A variable name cannot start with a number
    * A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
    * Variable names are case-sensitive (age, Age and AGE are three different variables)
    * A variable name cannot be any of the Python keywords.


In [ ]:
x = 5
x=7
y = "John"
y=9
print(x)
print(y)

7
9


In [ ]:
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)

Sally


**Casting**

If you want to specify the data type of a variable, this can be done with casting.

In [ ]:
var = str(3)    # var will be '3'
var1 = int(3)    # var1 will be 3
var2 = float(3)  # var2 will be 3.0
print(var)
print(var1)
print(var2)

3
3
3.0


In [ ]:
var=33
var

33

Legal variable names:

In [ ]:
# Valid or Legal Identifiers
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar27 = "John"
print(my_var)
print(myvar)
print(_my_var)
print(myVar)
print(MYVAR)

John
John
John
John
John


In [ ]:
print("My name is:", myVar)

My name is: John


In [ ]:
name="Alexander"
height="1.75cm"
weight=90
address="Dublin"
Workplace="DBS"

In [ ]:
print(f"I work at {Workplace}, and my name is {name}, I have a height of, {height} and weigh a total of {weight}kg")

I work at DBS, and my name is Alexander, I have a height of, 1.75cm and weigh a total of 90kg


In [ ]:
print("I work at", Workplace, "My name is", name, "My height is", height, "and I weigh about", weight, "Kg")

I work at DBS My name is Alexander My height is 1.75 and I weigh about 90 Kg


In [ ]:
myvar
my_var
_my_var
myVar
MYVAR
myvar27

'John'

Illegal variable names:

In [ ]:
# Invalid or Illegal Identifies
2myvar = "John"
my-var = "John"
my var = "John"

SyntaxError: invalid decimal literal (<ipython-input-30-14a598c60896>, line 2)

**Examples of Valid and Invalid Variables**

In [ ]:
# Valid variable names
name = "Alice"
_age = 30
favorite_color = "blue"

print(name)
print(_age)
print(favorite_color)

Alice
30
blue


In [ ]:
# Invalid variable names
1st_name = "Bob"  # Starts with a digit
age$ = 25  # Contains special character $
class = "Python"  # Uses a Python keyword

print(1st_name)
print(age$)
print(class)

SyntaxError: invalid decimal literal (<ipython-input-3-536ad9558576>, line 2)

**Declaring and Redeclaring Variables**

In [ ]:
# Assigning values to variables
counter = 10
marker = "Hello, World!"

# Reassigning variables to different data types
counter = "Python"
marker = 3.14

print(counter)
print(marker)

Python
3.14


In [ ]:
# declaring the var
Number = 100

# display
print("Before declare: ", Number)

# re-declare the var
Number = 120.3

print("After re-declare:", Number)

Before declare:  100
After re-declare: 120.3


**Variable Types**

Variable data types depend on the data types of the data assigned to them.

In [ ]:
# Different variable types
age = 25  # Integer
height = 5.8  # Float
name = "Alice"  # String
fruits = ["apple", "banana", "cherry"]  # List
person = {"name": "Bob", "age": 30}  # Dictionary

In [ ]:
# Variable example
name = "Alice"
age = 25
height = 5.6

# Print variables
print("Name:", name)
print("Age:", age)
print("Height:", height)

# Calculate BMI using variables
weight = 65
bmi = weight / (height ** 2)
print("BMI:", bmi)

Name: Alice
Age: 25
Height: 5.6
BMI: 2.0727040816326534


**Local and Global Variable Declaration**

In [ ]:
# This function uses local variable s
def f():
  s = "Welcome students"
  print(s)

In [ ]:
f()

NameError: name 'f' is not defined

In [ ]:
s=45

In [ ]:
f()

NameError: name 'f' is not defined

In [ ]:
# This function has a variable with
# name same as s
def f():
    print(s)

# Global scope
s = "I love Dublin Business School"

In [ ]:
f()

45


In [ ]:
s=45

In [ ]:
f()

45


In [ ]:
s="Bank Holiday"

In [ ]:
f()

Bank Holiday


In [ ]:
def f(x):
  print(x)
x=3

In [ ]:
f(x)

3


In [ ]:
x=345
f(x)

345


**An Example**

In [ ]:
x = 15

def change():

    # using a global keyword
    global x

    # increment value of a by 5
    x = x + 5
    print("Value of x inside a function :", x)


change()
print("Value of x outside a function :", x)

Value of x inside a function : 20
Value of x outside a function : 20


**Many Values to Multiple Variables**

Python allows you to assign values to multiple variables in one line:

In [ ]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


Unpack a Collection

In [ ]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


In [ ]:
tax =12.5/100
price=100.5
profit=price*tax

print(profit)

12.5625


In [ ]:
price +_ #This adds the last estimation above to the original value of price

414.5625

In [ ]:
round(_,2) #Rounds the last value to 2 decimal places

414.56

**2. Strings**

In [ ]:
"First Name"

'First Name'

In [ ]:
'spam eggs' #Ensure they are enclosed in single quotes

'spam eggs'

In [ ]:
'"Yes," they said it.'

'"Yes," they said it.'

In [ ]:
'Isn\'t, they said it', 71*2

("Isn't, they said it", 142)

In [ ]:
s= 'First line. Second line. Third Line'
s

'First line. Second line. Third Line'

In [ ]:
print(s)

First line. Second line. Third Line


In [ ]:
s='First line.\nSecond line \nThird Line' #\n means a new line
s #without using print()

'First line.\nSecond line \nThird Line'

In [ ]:
print(s) #using print shows the second line on a new line

First line.
Second line 
Third Line


In [ ]:
x='Today is my second day in the class introduction to Programming. \nI hope to learn new things. \nAfter class I am having Kebbab for lunch'


In [ ]:
x

'Today is my second day in the class introduction to Programming. \nI hope to learn new things. \nAfter class I am having Kebbab for lunch'

In [ ]:
print(x)

Today is my second day in the class introduction to Programming. 
I hope to learn new things. 
After class I am having Kebbab for lunch


In [ ]:
s='I am learning python today,\nI now feel like a programmer, \n I have always wanted to write my own codes, \n This module will give me the skills to do so.'

In [ ]:
s

'I am learning python today,\nI now feel like a programmer, \n I have always wanted to write my own codes, \n This module will give me the skills to do so.'

In [ ]:
print(s)

I am learning python today,
I now feel like a programmer, 
 I have always wanted to write my own codes, 
 This module will give me the skills to do so.


**Try an exercise, creating your own poem as above**

In [ ]:
print('C:\some\name line') #Note that name was cut to ame in the new line because \n means new line

C:\some
ew line


In [ ]:
print(r'C:\some\name') # The r before the quote made it seem like a raw string

C:\some\name


In [ ]:
#String literals can span multiple lines, this can be done by using multiple quotes (triple-quotes)
print ("""\
Usage: thingy [Options]
      -h              Display this usage message
      -H hostname     Hostname to connet to
""")

Usage: thingy [Options]
      -h              Display this usage message
      -H hostname     Hostname to connet to



**String Concatenation**

In [ ]:
#Strings can be concatenared with the + operator and repeated multiple times with the * operator
3*'Alex'+3*'Victor'

'AlexAlexAlexVictorVictorVictor'

In [ ]:
3*'hm'+'mmm'

'hmhmhmmmm'

In [ ]:
3*'un'+'ium'

'unununium'

In [ ]:
# Two or more strings literals next tow each other are automatically concatenated

In [ ]:
'Alex' 'ander'

'Alexander'

In [ ]:
'Py' 'thon'

'Python'

In [ ]:
'Te' 'chn' 'ica' 'lly'

'Technically'

In [ ]:
text=('we can put several str' 'ing within parenhesis to have them joined together')
text

'we can put several string within parenhesis to have them joined together'

In [ ]:
s='Py' #Variable s and literals can be concatenated

In [ ]:
s+'thon'

'Python'

In [ ]:
s+'ople'

'Pyople'

In [ ]:
s+'ep'

'Pyep'

In [ ]:
w='ep'

In [ ]:
s+w

'Peep'

In [ ]:
s+w+'ing'

'Peeping'

***String Indexing***

In [ ]:
word='Python is an easy programming language'

In [ ]:
word[0] #This picks the second letter from the left

'P'

In [ ]:
word[4] # This picks the third letter from the right. Recall that it starts counting from 0 not 1

'o'

In [ ]:
word[15:]

'sy programming language'

In [ ]:
word[:15]

'Python is an ea'

In [ ]:
word[20] #If you pick a number position out of range you get and error message

'o'

In [ ]:
word[-5]

'g'

***Slicing***

In [ ]:
word[0:15] # Characters from position 0 (included) to 2 (excluded)

'Python is an ea'

In [ ]:
word[:15]

'Python is an ea'

In [ ]:
word[2:15]

'thon is an ea'

In [ ]:
word[:2] + word[2:]

'Python is an easy programming language'

Always ensure that s[:i]+s[i:] is equal to s

In [ ]:
word[:3]+word[3:]

'Python is an easy programming language'

In [ ]:
word[:2]+word[3:]

'Pyhon is an easy programming language'

In [ ]:
word[:3]+word[1:]

'Pytython is an easy programming language'

**3. List**

Python can put a compound data together in form of list

In [ ]:
squares = [2,5,3,19, 24]

In [ ]:
squares*2

[2, 5, 3, 19, 24, 2, 5, 3, 19, 24]

In [ ]:
squares

[2, 5, 3, 19, 24]

***Indexing and Slicing List***

In [ ]:
squares[3:]

[19, 24]

In [ ]:
squares [:2]+squares[3:]

[2, 5, 19, 24]

In [ ]:
squares[2:5]

[3, 19, 24]

In [ ]:
squares[1:42]

[5, 3, 19, 24]

In [ ]:
squares[:42]

[2, 5, 3, 19, 24]

In [ ]:
squares[42:]

[]

In [ ]:
squares[-4]

5

In [ ]:
squares

[2, 5, 3, 19, 24]

In [ ]:
squares+[36,44,62,18,101] # List can support operations like concatenation

[2, 5, 3, 19, 24, 36, 44, 62, 18, 101]

In [ ]:
#The content of list can be changed/replace

In [ ]:
squares

[2, 5, 3, 19, 24]

In [ ]:
squares[2]=12

In [ ]:
squares

[2, 5, 12, 19, 24]

In [ ]:
squares[4]=4*4

In [ ]:
squares

[2, 5, 12, 19, 16]

In [ ]:
s=4*17
squares[2]=s
squares

[2, 5, 68, 19, 16]

In [ ]:
7*2

14

In [ ]:
7**2

49

In [ ]:
squares

[2, 5, 68, 12, 16]

In [ ]:
#New items can be added at the end of a list by using append() method

squares.append(225)
squares.append(7**2) # the square of 7
squares

[2, 5, 12, 19, 16, 225, 49]



---



**First Steps Towards Programming**

***4. While* Loops**

In [ ]:
i=1
while i<6:
  print(i)  #Print i as long as i is less than 6
  i+=1


1
2
3
4
5


In [ ]:
i=1
while i<6:

  i+=1
  print(i)  #Print i as long as i is less than 6


2
3
4
5
6


*Break statement*

In [ ]:
i=1  #Exit the loop when i is 3
while i<6:
  print(i)
  if i==2:
    break
  i+=1

1
2


In [ ]:
i=1 #Exit the loop when i is greater than 9
while i<11:
  print(i)
  if i>9:
    break
  i+=1

1
2
3
4
5
6
7
8
9
10


In [ ]:
i=0 #Continue to the next iteration if i is 3 (Skip 3)
while i<6:
  i+=1
  if i==3:
    continue
  print(i)


1
2
4
5
6


In [ ]:
i=1  #Print a message when the condition is false (exhausted)
while i<6:
  print(i)
  i+=1
else:
  print(" i is no longer less than 6")

1
2
3
4
5
 i is no longer less than 6


**The Fibonacci Series**

In [ ]:
a,b=0, 1
while a<1000:
    print(a, end=',')
    a,b=b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

a=0, b=1, a+b=0+1=1|a=b, b=a+b|a=1, b=1, a+b=2|a=1, b=2, a+b=3|a=2, b=3, a+b=5|a=3, b=5, a+b=8|a=5, b=8, a+b=13


**5. *if* Statements**

In [ ]:
a=20
b=200
if a>b:
  print("Clearly, a is greater than b")
elif a==b:
  print("a equal to b")
elif a<b:
  print("a is less than b")

a is less than b


In [ ]:
a=12
b=123
if b>a:
  print("b is greater than a")
elif a==b:
  print("a and be are equal")

b is greater than a


In [ ]:
a=200
b=33
if b>a:
  print("b is greater than a")
elif a==b:
  print("a and b are equal")
else:
  print("None of the conditions are true")

None of the conditions are true


In [ ]:
if b>a:
  print ("b is greater than a")
elif b==a:
  print("b is equal to a")
else:
  print("The class is over")

The class is over


In [ ]:
a=200
b=200

In [ ]:
print("Green") if a==b else print("Yellow")

Green


In [ ]:
print("Alexander") if b>a else print("Victor")

Victor


In [ ]:
a=200
b=330
c=500
if a>b and c>a:
  print("Both conditions are true")
else:
  print("The conditions is not satisfied")

The conditions is not satisfied


In [ ]:
a=200
b=33
c=500
if a>b and c>a:
  print("At least one of the conditions are true")
else:
  print("No condition is true")

At least one of the conditions are true


In [ ]:
x=2
if x < 3:
  x=0
  print('Negative changed to zero')
elif x==0:
  print('zero')
elif x==2:
  print('Single')
else:
  print('Anything else')

Negative changed to zero


In [ ]:
x=23 #Keep changing values of x and run it to see the output
if x>10:
  print("Above ten,")
  if x>20:
    print("and also above 20!")
  else:
    print("but not above 20.")

Above ten,
and also above 20!


**6. *for* Statements**

In [ ]:
words=['cat','window', 'technical']
for i in words:
  print(i)

cat
window
technical


In [ ]:
fruits=['apple', 'banana', 'cherry'] #Loops through the variable fruits and prints each fruit with their character length
for x in fruits:
  print(x, len(x))

apple 5
banana 6
cherry 6


In [ ]:
fruits=['apple', 'banana', 'cherry'] #Loops through the variable fruits and prints each fruit
for x in fruits:
  print(x)

apple
banana
cherry


In [ ]:
s=[2,43,5,78,5,3,3]
for x in s: #Loops through the letters in the word "banana"
  print(x)

2
43
5
78
5
3
3


In [ ]:
fruit="banana"
for x in fruit:
  print(x)

b
a
n
a
n
a


break statement

In [ ]:
fruits=['apple', 'banana', 'cherry'] #Exits the loop when x is banana
for x in fruits:
  print(x)
  if x=="banana":
    break

apple
banana


In [ ]:
fruits=['apple', 'banana', 'cherry'] #Exits the loop when x is banana and breaks before the print
for x in fruits:
  if x=="banana":
    break
  print(x)

apple


continue statement

In [ ]:
fruits=['apple', 'banana', 'cherry'] #Do not print banana
for x in fruits:
  if x=="banana":
    continue
  print(x)

apple
cherry


The range() function

In [ ]:
for x in range(6):  #Starts with 0 and increment by 1 and ends at the specific range
  print(x)

0
1
2
3
4
5


In [ ]:
for i in range(4):
  print(i)

0
1
2
3


In [ ]:
for x in range(2,6): #Starts with 2 but not including 6
  print(x)

2
3
4
5


In [ ]:
for i in range(2,30,3): #Starts with 2, increment by 3 and less than 30
  print(i)

2
5
8
11
14
17
20
23
26
29


*Else* in *For* Loop

In [ ]:
for x in range(6):
  print(x)
else:
  print("The end!")

0
1
2
3
4
5
The end!


In [ ]:
for x in range(8):
  if x==8:
    break
  print(x)
else:
  print("Finally finished")

0
1
2
3
4
5
6
7
Finally finished


Nested Loops

In [ ]:
adj=["red","big","tasty", "fresh"]
fruits=["apple","banana","cherry"]
prices=[2,3,4,5,6,7]

for x in adj:
  for y in fruits:
    for z in prices:

      print(x,y,z)

red apple 2
red apple 3
red apple 4
red apple 5
red apple 6
red apple 7
red banana 2
red banana 3
red banana 4
red banana 5
red banana 6
red banana 7
red cherry 2
red cherry 3
red cherry 4
red cherry 5
red cherry 6
red cherry 7
big apple 2
big apple 3
big apple 4
big apple 5
big apple 6
big apple 7
big banana 2
big banana 3
big banana 4
big banana 5
big banana 6
big banana 7
big cherry 2
big cherry 3
big cherry 4
big cherry 5
big cherry 6
big cherry 7
tasty apple 2
tasty apple 3
tasty apple 4
tasty apple 5
tasty apple 6
tasty apple 7
tasty banana 2
tasty banana 3
tasty banana 4
tasty banana 5
tasty banana 6
tasty banana 7
tasty cherry 2
tasty cherry 3
tasty cherry 4
tasty cherry 5
tasty cherry 6
tasty cherry 7
fresh apple 2
fresh apple 3
fresh apple 4
fresh apple 5
fresh apple 6
fresh apple 7
fresh banana 2
fresh banana 3
fresh banana 4
fresh banana 5
fresh banana 6
fresh banana 7
fresh cherry 2
fresh cherry 3
fresh cherry 4
fresh cherry 5
fresh cherry 6
fresh cherry 7


In [ ]:
adj=["red","big","tasty"]
fruits=["apple","banana","cherry"]

for x in adj:
  for y in fruits:
    print(x,  y, len(x), len(y))

red apple 3 5
red banana 3 6
red cherry 3 6
big apple 3 5
big banana 3 6
big cherry 3 6
tasty apple 5 5
tasty banana 5 6
tasty cherry 5 6


In [ ]:
adj=["red","big","tasty"]
fruits=["apple","banana","cherry"]

for x in adj:
  for y in fruits:
    print(x, len(x), y, len(y))

red 3 apple 5
red 3 banana 6
red 3 cherry 6
big 3 apple 5
big 3 banana 6
big 3 cherry 6
tasty 5 apple 5
tasty 5 banana 6
tasty 5 cherry 6


In [ ]:
a=['Mary','had','a','little','lamb']
for i in range(len(a)):
  print(i,a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [ ]:
for n in range(2,20):
  for x in range(2,n):
    if n % x==0:
      print(n, 'equals', x, '*', n//x)
      break

  else:
    #Loop fell through without finding a factor/multiple
    print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3
10 equals 2 * 5
11 is a prime number
12 equals 2 * 6
13 is a prime number
14 equals 2 * 7
15 equals 3 * 5
16 equals 2 * 8
17 is a prime number
18 equals 2 * 9
19 is a prime number


**Defining Functions**

Defining the Fibonacci series

In [ ]:
PI = 3.14159

def calculate_area(radius):
    area = PI * radius**2
    return area

radius = 5
area = calculate_area(radius)
print(f"The area of the circle is {area}")

The area of the circle is 78.53975


In [ ]:
def fib(n):
  a,b=0,1
  while a<n:
    print(a, end=' ')
    a,b=b,a+b
  print()

Now call the "fib" function we just defined and use it as you please

In [ ]:
fib(1000)


0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 


In [ ]:
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


In [ ]:
fib(10)

0 1 1 2 3 5 8 


In [ ]:
fib

<function __main__.fib(n)>

In [ ]:
f=fib
f(1000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 


In [ ]:
fib(0)
print(fib(0))



None


**Default Argument Values**

The most useful form is to specify a default value for one or more arguments. This creates a function that
can be called with fewer arguments than it is defined to allow. For example:


In [ ]:
def ask_ok(prompt, retries=4, reminder='Please try again later'):
  while True:
    ok=input(prompt)
    if ok in ('y', 'ye', 'yes'):
      return True
    if ok in ('n', 'no', 'nop', 'nope'):
      return False
    retries = retries - 1
    if retries < 0:
      raise ValueError('invalid user response')

    print(reminder)
response=ask_ok("Do you want to continue (Y/N):")
print(f"User response: {response}")

Do you want to continue (Y/N):e
Please try again later
Do you want to continue (Y/N):w
Please try again later
Do you want to continue (Y/N):y
User response: True


This function can be called in several ways:
*   giving only the mandatory argument: ask_ok('Do you really want to quit?')
*   giving one of the optional arguments: ask_ok('OK to overwrite the file?', 2)
*   or even giving all arguments: ask_ok('OK to overwrite the file?', 2, 'Come on, only yes or
no!')
This example also introduces the in keyword. This tests whether or not a sequence contains a certain value.

**Keyword Arguments**

Functions can also be called using keyword arguments of the form kwarg=value. For instance, the following
function:


In [ ]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
  print("-- This parrot wouldn't", action, end=' ')
  print("if you put", voltage, "volts through it.")
  print("-- Lovely plumage, the", type)
  print("-- It's", state, "!")

accepts one required argument (voltage) and three optional arguments (state, action, and type). This
function can be called in any of the following ways:

In [ ]:
parrot(1000) # 1 positional argument
parrot(voltage=1000) # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM') # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000) # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump') # 3 positional arguments
parrot('a thousand', state='pushing up the daisies') # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


**Another Example**

In [ ]:
def cheeseshop(kind, *arguments, **keywords):
  print("-- Do you have any", kind, "?")
  print("-- I'm sorry, we're all out of", kind)
  for arg in arguments:
    print(arg)
  print("-" * 40)
  for kw in keywords:
    print(kw, ":", keywords[kw])

It could be called like this:

In [ ]:
cheeseshop("Limburger", "It's very runny, sir.",
"It's really very, VERY runny, sir.",
shopkeeper="Michael Palin",
client="John Cleese",
sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


**Arbitrary Arguments Lists**

Finally, the least frequently used option is to specify that a function can be called with an arbitrary number
of arguments. These arguments will be wrapped up in a tuple. Before the
variable number of arguments, zero or more normal arguments may occur.

In [ ]:
def write_multiple_items(file, separator, *args):
  file.write(separator.join(args))

Normally, these variadic arguments will be last in the list of formal parameters, because they scoop up
all remaining input arguments that are passed to the function.

In [ ]:
def concat(*args, sep="/"):
  return sep.join(args)

In [ ]:
concat("earth", "mars", "venues")

'earth/mars/venues'

In [ ]:
concat("earth", "mars", "venues", sep=".")

'earth.mars.venues'

**Lambda Expressions**

Lambda functions can be used wherever function objects are required.
They are syntactically restricted to a single expression.

In [ ]:
def make_increments(n):
  return lambda x:x+n


In [ ]:
f=make_increments(42)

In [ ]:
f(3)

45

In [ ]:
f(100)

142

In [ ]:
f(-26)

16

**Input and Output**

To use formating strings literals, beign a string with f or F before opening quatation mark or triple quotation marks.

In [ ]:
year=2024; event="Constitutional Review"
f'Results of the {year} {event}'
print("Results of the", year, event)

Results of the 2024 Constitutional Review


In [ ]:
name="Jason"; activity="Loves to write python program"; frequency="24/7"
f'There is a student called {name} who {activity} {frequency}'

'There is a student called Jason who Loves to write python program 24/7'

**Manuel String Formatting**

In [ ]:
for x in range (1,11):
  print(repr(x).rjust(2), repr(x*x).rjust(3), end='')
  print(repr(x*x*x).rjust(4))

 1   1   1
 2   4   8
 3   9  27
 4  16  64
 5  25 125
 6  36 216
 7  49 343
 8  64 512
 9  81 729
10 1001000


**Reading and Writing Files**

The first argument is a string containing the filename. The second argument is another string containing a
few characters describing the way in which the file will be used. mode can be 'r' when the file will only
be read, 'w' for only writing (an existing file with the same name will be erased), and 'a' opens the file
for appending; any data written to the file is automatically added to the end. 'r+' opens the file for both
reading and writing.

In [ ]:
f=open('workfile', 'w')

In [ ]:
f=open('workfile', 'r')

In [ ]:
with open('workfile') as f:
  read_data=f.read()

In [ ]:
f.closed

True

**NumPy Basics: Arrays and Vectorized Computation**

In [ ]:
import numpy as np


In [ ]:
my_array=np.arange(1_000_000)

In [ ]:
my_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
my_list=list(range(1_000_000))

**The NumPy ndarray: A multidimensional array object**

One of the key features of NumPy is its N-dimensional array object, or ndarray,
which is a fast, flexible container for large datasets in Python. Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar eleme

In [ ]:
import numpy as np
data=np.array([[1.5, -0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
data*5

array([[  7.5,  -0.5,  15. ],
       [  0. , -15. ,  32.5]])

In [ ]:
data/4

array([[ 0.375, -0.025,  0.75 ],
       [ 0.   , -0.75 ,  1.625]])

In [ ]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
data2=np.array([[2,-0.5,6.1],[2.1,0,0.75]])
data2

array([[ 2.  , -0.5 ,  6.1 ],
       [ 2.1 ,  0.  ,  0.75]])

In [ ]:
data+data2

array([[ 3.5 , -0.6 ,  9.1 ],
       [ 2.1 , -3.  ,  7.25]])

In [ ]:
data1=data+data2
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
datas=data+data1+data2
datas

array([[ 7. , -1.2, 18.2],
       [ 4.2, -6. , 14.5]])

In [ ]:
data.shape

(2, 3)

**Creating ndarrays**

In [ ]:
data_new=[6,7.5,8,0,1]
arr1=np.array(data_new)

In [ ]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimen‐
sional array:

In [ ]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
 np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2,3,2))

array([[[6.62128759e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Arithmetic with NumPy Arrays**

In [ ]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [ ]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [ ]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

**Boolean Indexing**

In [ ]:
names=np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [ ]:
data=np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [ ]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Suppose each name corresponds to a row in the data array and we wanted to
select all the rows with the corresponding name "Bob". Like arithmetic operations,
comparisons (such as ==) with arrays are also vectorized. Thus, comparing names
with the string "Bob" yields a Boolean array:

In [ ]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

This Boolean array can be passed when indexing the

In [ ]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
data[names=="Bob",1:]

array([[7],
       [0]])

In [ ]:
data[names=="Bob",:1]

array([[4],
       [0]])

**Fancy Indexing**

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
Suppose we had an 8 × 4 array

In [ ]:
arr=np.zeros((8,4))

In [ ]:
for i in range(8):
  arr[i]=i

In [ ]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr=np.arange(32).reshape((8,4))

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

**Transposing Arrays and Swapping Axes**

Transposing is a special form of reshaping that similarly returns a view on the
underlying data without copying anything. Arrays have the transpose method and
the special T attribute:

In [ ]:
arr=np.arange(15).reshape((3,5))

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Dot product

In [ ]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [ ]:
arr.T@arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Array-Oriented Programming with Arrays**

Using NumPy arrays enables you to express many kinds of data processing tasks as
concise array expressions that might otherwise require writing loops. This practice
of replacing explicit loops with array expressions is referred to by some people
as *vectorization*.

As a simple example, suppose we wished to evaluate the function sqrt(x^2 +
y^2) across a regular grid of values. The numpy.meshgrid function takes two one-
dimensional arrays and produces two two-dimensional matrices corresponding to all
pairs of (x, y) in the two arrays

In [ ]:
points=np.arange(-5,5,0.01) #100 equally space points

In [ ]:
xs, ys=np.meshgrid(points, points)

In [ ]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [ ]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

Now, evaluating the function is a matter of writing the same expression you would
write with two points

In [ ]:
z=np.sqrt(xs**2+ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5,5,-5,5])
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")

Text(0.5, 1.0, 'Image plot of $\\sqrt{x^2+y^2}$ for a grid of values')

**Mathematical and Statistical Methods**

A set of mathematical functions that compute statistics about an entire array or
about the data along an axis are accessible as methods of the array class. You can
use aggregations (sometimes called reductions) like sum, mean, and std (standard
deviation) either by calling the array instance method or using the top-level NumPy
function. When you use the NumPy function, like numpy.sum, you have to pass the
array you want to aggregate as the first argum

In [ ]:
arr.mean()

7.0

In [ ]:
arr.sum()

105

In [ ]:
np.mean(arr)

7.0

In [ ]:
np.sum(arr2)

26.0

In [ ]:
arr.mean(axis=1)

array([ 2.,  7., 12.])

In [ ]:
arr.sum(axis=0)

array([15, 18, 21, 24, 27])

Other methods like cumsum and cumprod do not aggregate, instead producing an array
of the intermediate result

In [ ]:
arr.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [ ]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Linear Algebra**

Linear algebra operations, like matrix multiplication, decompositions, determinants,
and other square matrix math, are an important part of many array libraries. Multi‐
plying two two-dimensional arrays with * is an element-wise product, while matrix multiplications require using a function. Thus, there is a function dot, both an array
method and a function in the numpy namespace, for matrix multiplication.

In [ ]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])

In [ ]:
y=np.array([[6.,23.],[-1,7],[8,9]])

In [ ]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [ ]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])